cart/urls.py
from django.urls import path
from .views import cart_detail, add_to_cart

app_name = "cart"

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart, name='cart_add'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

router = DefaultRouter()


urlpatterns =[
    path('admin/', admin.site.urls),
    path('', include('users.urls')),  
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<h3>{{ request.user }}</h3>

<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for product in products %}
 <div class="col">
  <div class="card h-100 border rounded-4 shadow-sm" style="width: 18rem; border-color: #2e2e3e; background-color: #f9f9fb;">
    {% if product.images.all %}
        <img src="{{ product.images.first.image.url }}" class="card-img-top" alt="{{ product.name }}">
      {% else %}
        <img src="{% static 'img/no-image.png' %}" class="card-img-top" alt="Нет фото">
      {% endif %}
    <div class="card-body">
      <h5 class="card-title">{{ product.name }}</h5>
      <p class="card-text text-muted" style="font-size: 0.9rem;">{{ product.description|truncatewords:20 }}</p>
      <p class="card-text fw-semibold" style="color: #2e7d32;">{{ product.formatted_price }}</p>
      <a href="{% url 'cart:cart_add'  product.id %}" class="btn btn-outline-primary w-100 d-flex align-items-center justify-content-center gap-2">
        <i class="bi bi-cart-plus"></i> Добавить в корзину
      </a>
    </div>
  </div>
</div>

  {% empty %}
  <div class="col-12">
    <div class="alert alert-warning text-center" role="alert">
      В этой категории пока нет товаров.
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}